# Generated by Django 3.1.4 on 2020-12-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producent',
            new_name='manufacturer',
        ),
    ]
