# Generated by Django 3.1.4 on 2020-12-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0002_auto_20201202_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsonshelves',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shelf',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shelf',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
